### ISSUE TITLE
Issue with reformatting UTF8 documents

### ISSUE THREAD

**Issue by machlintosh** [textmate/json.tmbundle#13]
Example:
{"Hello": "World","中国": "上海"}

After Reformatting:
{
    "Hello": "World",
    "\u4e2d\u56fd": "\u4e0a\u6d77"
}

**Comment by ejb** [comment]
This is still an issue. Using the "Reformat Document" command messes up UTF8 characters. In addition to the examples above, the euro symbol `€` becomes `\u20ac`. I took a glance over the code but not sure where/how this can be fixed.

**Comment by infininight** [comment]
Corrected in #15 via 9745b438c50167ae6dfe39881c0bf5f613e6f77e. The new command requires 10.9+ for support reasons.
