### ISSUE TITLE
Weird comments formatting

### ISSUE THREAD

**Issue by moldcraft** [textmate/json.tmbundle#14]
[This file](https://github.com/moldcraft/dockerfiles/blob/21d1cbd261a6e15a5879db10e450da7cffc6e5b3/backup/build/home/host/btsync/config.json) contains comments and they are displayed like this

![](https://static.md/f7d97abe78eede3d4e0652f3ee63f9bd.png)

Whey this happens?

*[Github uses this formatter for json](https://github.com/github/linguist/tree/master/vendor/grammars)*

**Comment by infininight** [comment]
Comments are not part of the [official](http://json.org) [spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf), the reasoning [noted here](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr) by one of the authors. So any comment support you are seeing would be implementation specific and not suitable for inclusion into the grammar.
